# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [17]:
# Create a 1-dimensional NumPy array using np.array()
one_d = np.array([1,2,3])
one_d

# Create a 2-dimensional NumPy array using np.array()
two_d = np.array([[1,2,3],[4,5,6]])
two_d.shape

# Create a 3-dimensional Numpy array using np.array()
three_d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12], [13,14,15], [16,17,18]]])
three_d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [18]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one_d, one_d.shape, one_d.size, type(one_d)

(array([1, 2, 3]), (3,), 3, numpy.ndarray)

In [14]:
# Attributes of 2-dimensional array
two_d, two_d.shape, two_d.size, type(two_d)

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3),
 6,
 numpy.ndarray)

In [19]:
# Attributes of 3-dimensional array
three_d, three_d.shape, three_d.size, type(three_d)

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
 (2, 3, 3),
 18,
 numpy.ndarray)

In [20]:
one_d.ndim, two_d.ndim, three_d.ndim

(1, 2, 3)

In [21]:
one_d.dtype, two_d.dtype, three_d.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [23]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(two_d)
df

0  1  2
0  1  2  3
1  4  5  6

In [26]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
# Create an array of shape (7, 2, 3) of only zeros
ones2 = np.ones((7,2,3))
ones2

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [29]:
# Create an array within a range of 0 and 100 with step 3
arr_range = np.arange(0, 100, 3)
arr_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [32]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
ran = np.random.randint(0, 10, size=(7,2))
ran

array([[2, 1],
       [0, 2],
       [3, 4],
       [5, 6],
       [8, 0],
       [4, 0],
       [3, 2]])

In [33]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
ran1 = np.random.rand(3,5)
ran1

array([[0.04823664, 0.86251202, 0.92465084, 0.60207852, 0.12890767],
       [0.94192845, 0.09749213, 0.34438516, 0.66517362, 0.73995091],
       [0.07163035, 0.37569582, 0.31397139, 0.17862792, 0.57614534]])

In [44]:
# Set the random seed to 42
np.random.seed(3)


# Create a random array of numbers between 0 & 10 of size (4, 6)
ran2 = np.random.randint(0,10, size = (4,6))
ran2

array([[8, 9, 3, 8, 8, 0],
       [5, 3, 9, 9, 5, 7],
       [6, 0, 4, 7, 8, 1],
       [6, 2, 2, 1, 3, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [46]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
ran3 = np.random.randint(1,10, size=(3,7))
ran3
# Find the unique numbers in the array you just created
np.unique(ran3)

array([1, 2, 3, 4, 5, 6, 8])

In [47]:
# Find the 0'th index of the latest array you created
ran3[0]

array([8, 6, 2, 2, 2, 6, 6])

In [49]:
# Get the first 2 rows of latest array you created
ran3[:2]

array([[8, 6, 2, 2, 2, 6, 6],
       [8, 5, 4, 1, 1, 1, 1]])

In [50]:
# Get the first 2 values of the first 2 rows of the latest array
ran3[:2,:2]

array([[8, 6],
       [8, 5]])

In [53]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ran4 = np.random.randint(0,10, size=(3,5))
ones_1 = np.ones((3,5))
ran4, ones_1

(array([[2, 7, 2, 1, 3],
        [2, 4, 1, 2, 2],
        [7, 3, 4, 1, 6]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [54]:
# Add the two arrays together
ones_1 + ran4

array([[3., 8., 3., 2., 4.],
       [3., 5., 2., 3., 3.],
       [8., 4., 5., 2., 7.]])

In [61]:
# Create another array of ones of shape (5, 3)
ones_2 = np.ones((5,3)).reshape((3,5))
ones_2


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
# Try add the array of ones and the other most recent array together
ones_2 + ran4

array([[3., 8., 3., 2., 4.],
       [3., 5., 2., 3., 3.],
       [8., 4., 5., 2., 7.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [63]:
# Create another array of ones of shape (3, 5)
on_1 = np.ones((3,5))
on_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [64]:
# Subtract the new array of ones from the other most recent array
ran4 - ones_1

array([[1., 6., 1., 0., 2.],
       [1., 3., 0., 1., 1.],
       [6., 2., 3., 0., 5.]])

In [65]:
# Multiply the ones array with the latest array
ran4 * ones_1

array([[2., 7., 2., 1., 3.],
       [2., 4., 1., 2., 2.],
       [7., 3., 4., 1., 6.]])

In [66]:
# Take the latest array to the power of 2 using '**'
ran4**2

array([[ 4, 49,  4,  1,  9],
       [ 4, 16,  1,  4,  4],
       [49,  9, 16,  1, 36]], dtype=int32)

In [67]:
# Do the same thing with np.square()
np.square(ran4)

array([[ 4, 49,  4,  1,  9],
       [ 4, 16,  1,  4,  4],
       [49,  9, 16,  1, 36]], dtype=int32)

In [68]:
# Find the mean of the latest array using np.mean()
np.mean(ran4)

3.1333333333333333

In [69]:
# Find the maximum of the latest array using np.max()
np.max(ran4)

7

In [70]:
# Find the minimum of the latest array using np.min()
np.min(ran4)

1

In [72]:
# Find the standard deviation of the latest array
np.std(ran4)

1.9955506062794353

In [73]:
# Find the variance of the latest array
np.var(ran4)

3.9822222222222217

In [74]:
# Reshape the latest array to (3, 5, 1)
ran4 = ran4.reshape((3,5,1))
ran4

array([[[2],
        [7],
        [2],
        [1],
        [3]],

       [[2],
        [4],
        [1],
        [2],
        [2]],

       [[7],
        [3],
        [4],
        [1],
        [6]]])

In [75]:
# Transpose the latest array
ran4.T

array([[[2, 2, 7],
        [7, 4, 3],
        [2, 1, 4],
        [1, 2, 1],
        [3, 2, 6]]])

What does the transpose do?

In [76]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ar1 = np.random.randint(0,10, size = (3,2))
ar2 = np.random.randint(0,10, size = (3,3))

In [77]:
# Perform a dot product on the two newest arrays you created
np.dot(ar1, ar2)

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [78]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ar3 = np.random.randint(0,10, size=(4,3))
ar4 = np.random.randint(0,10, size=(4,3))

In [79]:
# Perform a dot product on the two newest arrays you created
np.dot(ar3,ar4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [81]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
ar3 = ar3.T
np.dot(ar3,ar4)

array([[111,  87,  75],
       [130, 107,  63],
       [ 97,  67,  59]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [83]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ar3 = ar3.T
ar3>ar4

array([[False,  True,  True],
       [False,  True, False],
       [False, False,  True],
       [ True,  True, False]])

In [39]:
# Compare the two arrays with '>'


What happens when you compare the arrays with `>`?

In [84]:
# Compare the two arrays with '>='
ar3 >= ar4

array([[ True,  True,  True],
       [False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [85]:
# Find which elements of the first array are greater than 7
ar3 > 7

array([[False, False,  True],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False]])

In [86]:
# Which parts of each array are equal? (try using '==')
ar3 == ar4

array([[ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False, False]])

In [87]:
# Sort one of the arrays you just created in ascending order
np.sort(ar3)

array([[4, 7, 9],
       [0, 1, 9],
       [4, 7, 8],
       [1, 4, 8]])

In [88]:
# Sort the indexes of one of the arrays you just created
np.argsort(ar3)

array([[0, 1, 2],
       [2, 0, 1],
       [1, 0, 2],
       [2, 1, 0]], dtype=int64)

In [89]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(ar3)

2

In [90]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ar3)

5

In [94]:
ar3

array([[4, 7, 9],
       [1, 9, 0],
       [7, 4, 8],
       [8, 4, 1]])

In [92]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(ar3, axis=1)

array([2, 1, 2, 0], dtype=int64)

In [93]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(ar3, axis=0)

array([1, 2, 1], dtype=int64)

In [102]:
# Create an array of normally distributed random numbers
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [103]:
# Createan array with 10 evenly spaced numbers between 1 an
np.arange(1,100, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.